"""create buses, school_buses

Revision ID: 1cc2ddaa35ce
Revises: bf0135d7879d
Create Date: 2026-02-26 15:55:43.543977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc2ddaa35ce'
down_revision: Union[str, Sequence[str], None] = 'bf0135d7879d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('bus_code', sa.String(length=64), nullable=False),
    sa.Column('external_system', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_code'),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_buses_external_system_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('school_buses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('bus_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('color_name', sa.String(length=64), nullable=True),
    sa.Column('hex_color', sa.CHAR(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('is_sped', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('school_id', 'bus_id', name='uq_school_buses_school_bus'),
    sa.UniqueConstraint('school_id', 'display_name', name='uq_school_buses_school_display_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
